version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - event-platform-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - event-platform-network

networks:
  event-platform-network:
    external: true
